### ISSUE TITLE
Carla result

### ISSUE THREAD

**Issue by TairuiWang** [carla-simulator/imitation-learning#11]
Hi guys,

Currently, I am testing the released model. However, I found my result is not as good as the result of [this](https://arxiv.org/abs/1711.03938) paper.
For example, the result of 'new town' with 'straight' is 97%, but my test result is 71%. I checked each episode and found in many cases that the car stops at the start point and doesn't move at all. 
I didn't change any of the released code and my Carla version is 0.7.1.

Any ideas why could this happen? BTW, my command to launch Carla is:
`./CarlaUE4.sh /Game/Maps/Town01 -carla-server -benchmark -fps=10 -windowed -ResX=800 -ResY=600
`
Best,
Tairui

**Comment by mvpcom** [comment]
I can confirm the same problem

**Comment by dosovits** [comment]
Thanks for bringing this up! We investigated, and it seems the difference in the results is because one feature of the agent (that helps fighting this spontaneous stopping) got disabled in the release.
 
It can now be activated with the “--avoid-stopping” flag when running run_CIL.py . Please give it a try and let us know if this helps.

Again, thanks a lot for reporting this - this was an oversight on our side.

**Comment by mvpcom** [comment]
@TairuiWang Could you confirm with this new update you can produce the same result? Unfortunately, it seems to me the new update makes the model more unstable :(

**Comment by TairuiWang** [comment]
@mvpcom The result looks good to me. What do you mean 'unstable'?
