### ISSUE TITLE
the activation function for the control 

### ISSUE THREAD

**Issue by Fengmoon93** [carla-simulator/imitation-learning#12]
In the different branches 
for the steer, I think that the nonlinear function should be the tanh([-1,1]) which means the turning rate should be [-180 degrees~180 degrees]
for the brake and the gas, the activation function should be sigmoid ([0,1])
in the model, all the activation function is Relu
Is the output converted by the CARLA control?
I haven't run the code in the CARLA yet because now I'm using the Ubuntu 14.04

**Comment by felipecode** [comment]
Hey @Fengmoon93 
I think the non linearities inside the network should be Relu, since
they tend to be more stable.
Also from my tests, i saw that putting activation functions on the last layer doesn't produce good results.  The last layer from the network definition is:
`
 branches.append(network_manager.fc(branch_output, len(branch_config[i])))`

Maybe some problem with my code readability. 
The "fc" methods from the network manager have no dropout or activation function.

Thanks for your interest !
Hope you try it later.

**Comment by mvpcom** [comment]
@felipecode When and where the code will adjust the output between [-1,1]? I saw in the experiment; sometimes network even will produce numbers higher than 1.05 or so.  Is there any adjustment for applying control inputs?

**Comment by felipecode** [comment]
I don't adjust. It doest seem to be a problem. Yes eventually you have values slightly higher
than 1, but that is fine.
Maybe we could apply some threshold.
